Fixes "NoMethodError: undefined method `success?' for nil:NilClass"
Some ruby versions need to require 'English' otherwise $CHILD_STATUS is nil
Switch back to using $?